# admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjI5OTIyMTgsImV4cCI6MTYyMzAyMjIxOH0.1q4iOisbQ11uSDCZXGOc0F-pm28TzQU5-N2chRV3ztM
# eloluap: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZWxvbHVhcCIsImlhdCI6MTYyMjk5MjI1MCwiZXhwIjoxNjIzMDIyMjUwfQ.6k543nNKEQ0hCA9LWTneZ9kmf6lf09CXq65ODSWoMyI

# Email: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiUGF1bCIsImlhdCI6MTYyMzAwODM1OCwiZXhwIjoxNjIzMDM4MzU4fQ.xm20VsPNzydbgf6Cat0C4fUUV97IXAxB4h6id0He9MY
# Other token link: 9b20aeddad7d0119e8bae482b18e1aca269154cec78446a613fd1a9913029407d57cce1a657b1702cd81c0732251c1fa

### Registering a user - needs jsonbody user
POST https://localhost:8080/registration/
Content-Type: application/json 

{
    "user": 
    {
        "userID": "Peepao",
        "email": "paa.saalfeld@flohr-cie.de",
        "password": "PaulTest"
    }
}

### Clicking on Email link - needs inserted link
GET https://localhost:8080/registration/9b20aeddad7d0119e8bae482b18e1aca269154cec78446a613fd1a9913029407d57cce1a657b1702cd81c0732251c1fa